### ISSUE TITLE
Latest Version Crashing out v0.2.2

### ISSUE THREAD

**Issue by konradwalsh** [ewikner/org.mysensors.homey#26]
Auto update that came through yesterday is crashing

Stack trace:

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at /homey-app/manager/drivers.js:74:27
at Array.forEach (native)
at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:66:26)

Exit code: 1
Exit signal: null

**Comment by konradwalsh** [comment]
Confirmed fixed with 0.2.3
